.PHONY: build test upload upload-test clean

build:
	python setup.py sdist bdist_wheel

check:
	twine check dist/*

upload:
	twine upload -u __token__ -p "<your_api_token>" dist/*

upload-test:
	twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p "<your_api_token>" --verbose dist/*

clean:
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('dist')]"
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('build')]"
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('*.egg-info')]"

all: clean build check
