.PHONY: build test upload upload-test clean

build:
	python setup.py sdist bdist_wheel

check:
	twine check dist/*

upload:
	twine upload -u __token__ -p "pypi-AgEIcHlwaS5vcmcCJGNmNTE4NGE2LTlhMjEtNDU3ZS1hZjRlLWRjODVhODM1ODIwYwACKlszLCI0YWYwZDczMC0yNWQzLTQ2NjQtYTg4Ny1lZDQ4ZTliNzYyZjYiXQAABiC9NvRCfmt8TaPRzaJut5NkexM0KwaroGFaovLtrNgnLA" dist/*

upload-test:
	twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p "pypi-AgENdGVzdC5weXBpLm9yZwIkM2JkMjUwNzgtODM5OS00NTkxLThlNDktMzg2MTU2Yzk4MzkxAAIWWzEsWyJteS1ldGwtcGFja2FnZSJdXQACLFsyLFsiYmQzMjE4NzUtNmNiNC00ZWIwLWFhNjgtNjBjZDMxMjM0ZmU0Il1dAAAGIErBSoHF4j2gSgmWbWJrofWBhf2PrPSDx9XDaJRtLFn9" --verbose dist/*

clean:
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('dist')]"
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('build')]"
	python -c "import shutil, glob; [shutil.rmtree(d) for d in glob.glob('*.egg-info')]"

all: clean build check
